export * from './formatters';
export * from './validators';
export * from './errorHandling';
export * from './debug';
export * from './accessibility';
export * from './typeGuards';

export {
  isString,
  isNumber,
  isBoolean,
  isObject,
  isArray,
  isValidUUID,
  isValidDate,
  isValidPhoneNumber,
  isLengthBetween,
  isPositive,
  isNegative,
  isInteger,
  isWithinDecimalPlaces,
  validateProposal,
  validateProposalTitle,
  validateProposalSummary,
  validateProposalStatus,
  validateUserEmail,
  validateUserPassword,
  validateVoteChoice,
  validateVoteEligibility,
  validateMessageTitle,
  validateMessageBody,
  validateTopicState,
  validateUUID,
  validateStringLength,
  validateStringPattern,
  validateMinLength,
  validateMaxLength,
  validateNumberRange,
  validateMin,
  validateMax,
  validateMultipleFields,
  validateIf,
  validateOneOf,
  sanitizeString,
  sanitizeEmail,
  normalizeWhitespace,
  removeNonAlphanumeric,
  removeSpecialCharacters,
  capitalizeFirst,
  toSlug,
  composeValidators,
  createValidator,
  validateWhen,
  validateUnless,
  collectErrors,
  isAllValid,
  getFirstError,
  combineValidationResults,
  debounceValidation,
  coerceToString,
  coerceToNumber,
  coerceToBoolean,
  validateArray,
  validateArrayMinLength,
  validateArrayMaxLength,
  PROPOSAL_VALIDATION_RULES,
  USER_VALIDATION_RULES,
  MESSAGE_VALIDATION_RULES,
  VALID_VOTE_CHOICES,
  VALID_TOPIC_STATES,
  VALID_PROPOSAL_STATUSES,
  type ProposalValidationResult,
  type UserPasswordValidationResult,
  type VoteEligibilityResult,
  type ValidationResult,
  type PasswordValidationResult,
  type ProposalValidationRules,
  type VoteChoice,
  type TopicState,
  type ProposalStatus,
  type MultiFieldValidationResult
} from './validation';

export {
  ApplicationError,
  ValidationError,
  NotFoundError,
  AuthenticationError,
  AuthorizationError,
  NetworkError,
  TimeoutError,
  RateLimitError,
  ExternalServiceError,
  isApplicationError,
  formatError,
  handleError,
  tryCatchSync,
  safeAsync,
  safeSync,
  extractErrorMessage,
  getErrorStatusCode,
  isRetryableError,
  retryOnError,
  type ErrorResponse,
  type SafeResult
} from './errors';
