import { PageLayout } from '../../components/layout/PageLayout';
import { Link } from 'react-router-dom';
import {
  Vote, Lock, DollarSign, Zap, Award, Shield,
  TrendingUp, Users, Flame, Gift, Coins, ArrowRight,
  CheckCircle2, Star, Target
} from 'lucide-react';

export default function Utility() {
  const utilities = [
    {
      icon: <Vote className="w-8 h-8 text-cyan-400" />,
      title: 'Governance Voting',
      description: 'Vote on proposals to determine which businesses get built, governance parameters, and ecosystem decisions.',
      details: [
        'Vote on business proposals submitted to the launchpad',
        'Propose parameter changes (min. 50,000 AAIC required)',
        'Voting power = tokens held + staking multiplier + participation bonus',
        'Each token equals 1 vote (before multipliers)',
        'Delegation supported for maximum flexibility',
      ],
      example: '100,000 AAIC staked for 1 year = 200,000 voting power',
      link: '/governance',
    },
    {
      icon: <Lock className="w-8 h-8 text-purple-400" />,
      title: 'Staking Rewards',
      description: 'Lock your tokens to earn passive income and boost your governance power.',
      details: [
        'Lock periods: 30, 90, 180, or 365 days',
        'APY ranges from 5% (30 days) to 25% (365 days)',
        'Auto-compound option for maximizing returns',
        'Staked tokens multiply voting power (up to 2x)',
        'Rewards distributed from ecosystem revenue',
      ],
      example: '100,000 AAIC staked for 1 year = 25,000 AAIC rewards + 2x voting power',
      link: '/token/staking',
    },
    {
      icon: <DollarSign className="w-8 h-8 text-green-400" />,
      title: 'Revenue Share',
      description: 'Receive proportional distributions from profits generated by AI-managed businesses.',
      details: [
        '35% of ecosystem revenue goes to stakers',
        'Distributed quarterly in proportion to stake',
        'Revenue comes from all ecosystem businesses',
        'Claim anytime or auto-reinvest',
        'Paid in AAIC or stablecoins (your choice)',
      ],
      example: 'If you hold 1% of staked supply, you receive 1% of the 35% revenue pool',
      link: '/governance/treasury',
    },
    {
      icon: <Zap className="w-8 h-8 text-yellow-400" />,
      title: 'Platform Fee Discounts',
      description: 'Get discounted fees when using ecosystem products and services.',
      details: [
        '10% discount on proposal submission fees',
        '20% off AI business factory usage fees',
        '15% discount on premium features',
        'Tiered discounts based on holdings',
        'Discounts stack with staking bonuses',
      ],
      example: 'Holding 10,000+ AAIC = 20% off all platform fees',
      link: '/ecosystem',
    },
    {
      icon: <Star className="w-8 h-8 text-blue-400" />,
      title: 'Priority Access',
      description: 'Early access to new businesses, features, and exclusive opportunities.',
      details: [
        'First access to newly launched businesses',
        'Beta testing for new ecosystem features',
        'Priority in airdrop allocations',
        'Exclusive NFT drops for top holders',
        'Early bird pricing on new services',
      ],
      example: 'Top 1,000 holders get 48-hour early access to all new launches',
      link: '/launchpad',
    },
    {
      icon: <Flame className="w-8 h-8 text-orange-400" />,
      title: 'Buyback Participation',
      description: 'Benefit from deflationary token burns funded by ecosystem profits.',
      details: [
        '20% of revenue used for token buybacks',
        '50% of bought-back tokens are burned',
        'Burns create deflationary pressure',
        'Quarterly buyback events',
        'Transparent on-chain tracking',
      ],
      example: 'Last quarter: 250,000 AAIC burned = $312,500 removed from supply',
      link: '/token/tokenomics',
    },
    {
      icon: <Award className="w-8 h-8 text-indigo-400" />,
      title: 'Voting Rewards',
      description: 'Earn additional tokens for active participation in governance.',
      details: [
        '10% of revenue allocated to governance participants',
        'Rewards proportional to voting activity',
        'Bonus for voting on every proposal',
        'Extra rewards for thoughtful proposal creation',
        'Consistent voters earn 5-10% bonus APY',
      ],
      example: 'Vote on 20 proposals = ~2% additional annual return',
      link: '/governance/live',
    },
    {
      icon: <Users className="w-8 h-8 text-pink-400" />,
      title: 'Referral Bonuses',
      description: 'Grow the community and earn rewards for successful referrals.',
      details: [
        'Earn 5% of referred user\'s airdrop allocation',
        'Lifetime 2% of referee\'s staking rewards',
        'Bonus multipliers for multiple referrals',
        'Special rewards for high-value referrals',
        'No limit on total referral earnings',
      ],
      example: 'Refer 10 active users = 50,000+ bonus AAIC over time',
      link: '/token/airdrop',
    },
    {
      icon: <Shield className="w-8 h-8 text-teal-400" />,
      title: 'Proposal Submission',
      description: 'Submit your own business ideas to the ecosystem launchpad.',
      details: [
        'Minimum 50,000 AAIC required to submit',
        'Deposit refunded if proposal passes',
        'Proposers receive 20% equity in their business',
        'Treasury funds development costs',
        'Full transparency throughout process',
      ],
      example: 'Successful proposal = funded business + 20% ownership',
      link: '/launchpad/submit',
    },
    {
      icon: <Zap className="w-8 h-8 text-green-400" />,
      title: 'Use-to-Earn Rewards',
      description: 'Earn AAIC tokens automatically by using ecosystem services. The more you use, the more you earn.',
      details: [
        'Automatic rewards for platform usage',
        'No manual claims - accrues in real-time',
        'Rates adjust based on business profitability',
        'Sustainable model backed by real revenue',
        'Track usage and earnings in dashboard',
      ],
      example: 'Use AI Traders for 50 trades/month = ~250 AAIC earned ($25 at $0.10/token)',
      link: '/token/use-to-earn',
    },
    {
      icon: <Target className="w-8 h-8 text-emerald-400" />,
      title: 'Future Utilities',
      description: 'Upcoming features that will expand token utility.',
      details: [
        'Cross-chain bridge for multi-chain availability',
        'NFT marketplace with AAIC-exclusive collections',
        'Loyalty rewards program for long-term holders',
        'DAO treasury management participation',
        'Partnership perks and ecosystem integrations',
      ],
      example: 'Q2 2025: Cross-chain expansion to Arbitrum, Optimism, Polygon',
      link: '/ecosystem/roadmap',
    },
  ];

  return (
    <PageLayout>
      <div className="space-y-16">
        <section className="text-center max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-cyan-500/20 text-cyan-400 rounded-full text-sm font-medium mb-6">
            <Coins className="w-4 h-4" />
            Token Utility
          </div>

          <h1 className="text-5xl sm:text-6xl font-bold text-white mb-6 leading-tight">
            AAIC{' '}
            <span className="bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">
              Token Utility
            </span>
          </h1>

          <p className="text-xl text-slate-300 mb-8 leading-relaxed">
            AAIC is a multi-utility token powering governance, revenue sharing, staking rewards, and exclusive
            ecosystem access. Holding AAIC means owning a stake in a growing portfolio of AI-managed businesses.
          </p>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-slate-800/30 backdrop-blur border border-slate-700 rounded-xl p-4">
              <div className="text-3xl font-bold text-cyan-400 mb-1">10+</div>
              <div className="text-sm text-slate-400">Core Utilities</div>
            </div>
            <div className="bg-slate-800/30 backdrop-blur border border-slate-700 rounded-xl p-4">
              <div className="text-3xl font-bold text-green-400 mb-1">35%</div>
              <div className="text-sm text-slate-400">Revenue to Stakers</div>
            </div>
            <div className="bg-slate-800/30 backdrop-blur border border-slate-700 rounded-xl p-4">
              <div className="text-3xl font-bold text-purple-400 mb-1">25%</div>
              <div className="text-sm text-slate-400">Max Staking APY</div>
            </div>
            <div className="bg-slate-800/30 backdrop-blur border border-slate-700 rounded-xl p-4">
              <div className="text-3xl font-bold text-orange-400 mb-1">2x</div>
              <div className="text-sm text-slate-400">Max Vote Multiplier</div>
            </div>
          </div>
        </section>

        <section className="space-y-6">
          {utilities.map((utility, index) => (
            <div
              key={index}
              className="bg-slate-800/30 backdrop-blur border border-slate-700 rounded-2xl p-8 hover:border-slate-600 transition-colors"
            >
              <div className="flex items-start gap-6">
                <div className="p-4 bg-slate-700/50 rounded-xl flex-shrink-0">
                  {utility.icon}
                </div>

                <div className="flex-1">
                  <h2 className="text-2xl font-bold text-white mb-3">{utility.title}</h2>
                  <p className="text-slate-300 mb-6 text-lg">{utility.description}</p>

                  <div className="grid md:grid-cols-2 gap-4 mb-6">
                    <div>
                      <h3 className="text-sm font-semibold text-cyan-400 mb-3">Key Features</h3>
                      <ul className="space-y-2">
                        {utility.details.map((detail, idx) => (
                          <li key={idx} className="text-sm text-slate-300 flex items-start gap-2">
                            <CheckCircle2 className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                            <span>{detail}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    <div>
                      <h3 className="text-sm font-semibold text-cyan-400 mb-3">Example</h3>
                      <div className="bg-slate-900/50 rounded-xl p-4">
                        <p className="text-slate-300 text-sm">{utility.example}</p>
                      </div>

                      <Link
                        to={utility.link}
                        className="mt-4 inline-flex items-center gap-2 text-cyan-400 hover:text-cyan-300 text-sm font-medium"
                      >
                        Learn More
                        <ArrowRight className="w-4 h-4" />
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </section>

        <section className="bg-slate-800/30 backdrop-blur border border-slate-700 rounded-2xl p-8">
          <h2 className="text-3xl font-bold text-white mb-6 text-center">Token Flow Through Ecosystem</h2>
          <p className="text-slate-300 text-center mb-8 max-w-3xl mx-auto">
            Understand how AAIC tokens circulate through the ecosystem, creating value for all stakeholders.
          </p>

          <div className="max-w-4xl mx-auto">
            <div className="relative">
              <div className="space-y-6">
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-full bg-cyan-500 flex items-center justify-center text-white font-bold flex-shrink-0">
                    1
                  </div>
                  <div className="flex-1 bg-slate-900/50 rounded-xl p-4">
                    <h3 className="font-bold text-white mb-1">Token Distribution</h3>
                    <p className="text-sm text-slate-300">
                      100% airdrop to community, no token sale. Fair distribution ensures decentralization.
                    </p>
                  </div>
                  <ArrowRight className="w-6 h-6 text-slate-600 flex-shrink-0" />
                </div>

                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-full bg-blue-500 flex items-center justify-center text-white font-bold flex-shrink-0">
                    2
                  </div>
                  <div className="flex-1 bg-slate-900/50 rounded-xl p-4">
                    <h3 className="font-bold text-white mb-1">Users Acquire AAIC</h3>
                    <p className="text-sm text-slate-300">
                      Through airdrop, DEX purchases, or ecosystem participation rewards.
                    </p>
                  </div>
                  <ArrowRight className="w-6 h-6 text-slate-600 flex-shrink-0" />
                </div>

                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-full bg-purple-500 flex items-center justify-center text-white font-bold flex-shrink-0">
                    3
                  </div>
                  <div className="flex-1 bg-slate-900/50 rounded-xl p-4">
                    <h3 className="font-bold text-white mb-1">Staking & Governance</h3>
                    <p className="text-sm text-slate-300">
                      Users stake tokens to earn rewards and gain voting power on business proposals.
                    </p>
                  </div>
                  <ArrowRight className="w-6 h-6 text-slate-600 flex-shrink-0" />
                </div>

                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-full bg-green-500 flex items-center justify-center text-white font-bold flex-shrink-0">
                    4
                  </div>
                  <div className="flex-1 bg-slate-900/50 rounded-xl p-4">
                    <h3 className="font-bold text-white mb-1">Approved Businesses Launch</h3>
                    <p className="text-sm text-slate-300">
                      Treasury funds AI-built businesses. AI agents manage operations and generate revenue.
                    </p>
                  </div>
                  <ArrowRight className="w-6 h-6 text-slate-600 flex-shrink-0" />
                </div>

                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center text-white font-bold flex-shrink-0">
                    5
                  </div>
                  <div className="flex-1 bg-slate-900/50 rounded-xl p-4">
                    <h3 className="font-bold text-white mb-1">Revenue Generation</h3>
                    <p className="text-sm text-slate-300">
                      Businesses generate profits which flow back to the ecosystem treasury.
                    </p>
                  </div>
                  <ArrowRight className="w-6 h-6 text-slate-600 flex-shrink-0" />
                </div>

                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-full bg-pink-500 flex items-center justify-center text-white font-bold flex-shrink-0">
                    6
                  </div>
                  <div className="flex-1 bg-slate-900/50 rounded-xl p-4">
                    <h3 className="font-bold text-white mb-1">Revenue Distribution</h3>
                    <p className="text-sm text-slate-300">
                      15% Buyback, 15% Burn, 15% Staking, 15% U2E, 25% Treasury, 15% Variable (governance-controlled).
                    </p>
                  </div>
                  <ArrowRight className="w-6 h-6 text-slate-600 flex-shrink-0" />
                </div>

                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center text-white font-bold flex-shrink-0">
                    7
                  </div>
                  <div className="flex-1 bg-slate-900/50 rounded-xl p-4">
                    <h3 className="font-bold text-white mb-1">Token Burns</h3>
                    <p className="text-sm text-slate-300">
                      Regular burns reduce supply, creating deflationary pressure and increasing token value.
                    </p>
                  </div>
                  <div className="w-6 h-6 flex-shrink-0" />
                </div>
              </div>

              <div className="mt-8 bg-cyan-500/10 border border-cyan-500/30 rounded-xl p-6">
                <h3 className="text-white font-semibold mb-2">The Cycle Repeats</h3>
                <p className="text-slate-300 text-sm">
                  As more businesses launch and generate revenue, the flywheel accelerates. Higher revenue
                  means more rewards for stakers, larger buybacks, and increased demand for governance participation.
                  This creates a self-reinforcing cycle of value creation.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="bg-slate-800/30 backdrop-blur border border-slate-700 rounded-2xl p-8">
          <h2 className="text-3xl font-bold text-white mb-6">Utility Comparison</h2>

          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-slate-700">
                  <th className="text-left py-4 px-4 text-sm font-semibold text-slate-400">Feature</th>
                  <th className="text-center py-4 px-4 text-sm font-semibold text-slate-400">Hold Only</th>
                  <th className="text-center py-4 px-4 text-sm font-semibold text-slate-400">Staked</th>
                  <th className="text-center py-4 px-4 text-sm font-semibold text-slate-400">Active Voter</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-slate-800">
                  <td className="py-4 px-4 text-slate-300">Governance Voting</td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                </tr>
                <tr className="border-b border-slate-800">
                  <td className="py-4 px-4 text-slate-300">Staking Rewards</td>
                  <td className="py-4 px-4 text-center text-slate-600">-</td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                </tr>
                <tr className="border-b border-slate-800">
                  <td className="py-4 px-4 text-slate-300">Revenue Share</td>
                  <td className="py-4 px-4 text-center text-slate-600">-</td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                </tr>
                <tr className="border-b border-slate-800">
                  <td className="py-4 px-4 text-slate-300">Voting Power Multiplier</td>
                  <td className="py-4 px-4 text-center text-white">1x</td>
                  <td className="py-4 px-4 text-center text-white">up to 2x</td>
                  <td className="py-4 px-4 text-center text-white">up to 2.2x</td>
                </tr>
                <tr className="border-b border-slate-800">
                  <td className="py-4 px-4 text-slate-300">Voting Rewards</td>
                  <td className="py-4 px-4 text-center text-slate-600">-</td>
                  <td className="py-4 px-4 text-center text-slate-600">-</td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                </tr>
                <tr className="border-b border-slate-800">
                  <td className="py-4 px-4 text-slate-300">Platform Fee Discounts</td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                </tr>
                <tr>
                  <td className="py-4 px-4 text-slate-300">Priority Access</td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                  <td className="py-4 px-4 text-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mx-auto" />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className="mt-6 text-sm text-slate-400 text-center">
            Maximum benefits achieved by staking tokens and actively participating in governance
          </div>
        </section>

        <section className="bg-gradient-to-r from-cyan-500/10 to-blue-500/10 border border-cyan-500/30 rounded-2xl p-8 text-center">
          <h2 className="text-3xl font-bold text-white mb-4">Maximize Your AAIC Utility</h2>
          <p className="text-slate-300 mb-8 max-w-2xl mx-auto">
            Get the most value from your tokens by staking, voting, and actively participating in the ecosystem.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <Link
              to="/token/staking"
              className="px-6 py-3 bg-cyan-600 hover:bg-cyan-700 text-white font-medium rounded-lg transition-colors"
            >
              Start Staking
            </Link>
            <Link
              to="/governance"
              className="px-6 py-3 bg-slate-700 hover:bg-slate-600 text-white font-medium rounded-lg transition-colors"
            >
              View Governance
            </Link>
            <Link
              to="/token/airdrop"
              className="px-6 py-3 bg-slate-700 hover:bg-slate-600 text-white font-medium rounded-lg transition-colors"
            >
              Join Airdrop
            </Link>
          </div>
        </section>
      </div>
    </PageLayout>
  );
}
